[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"

solc = "0.8.26"
optimizer = true
optimizer_runs = 200

fs_permissions = [{ access = "read", path = "../" }]

[profile.default.fuzz]
runs = 256
max_test_rejects = 65536

[profile.ci.fuzz]
runs = 1000

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
